apiVersion: v1
kind: Secret
metadata:
  name: harbor-robot-account
  namespace: class-2
type: Opaque
stringData:
  username: <harbor-robot-id>       # 예: robot$skala26a-ai2
  password: <harbor-robot-password>
