apiVersion: v1
kind: Secret
metadata:
  name: sk047-myservice-secret
  namespace: class-2
type: Opaque
stringData:
  POSTGRES_DB: cloud
  POSTGRES_USER: skala
  POSTGRES_PASSWORD: "Skala25a!23$"
  POSTGRES_HOST: postgres-1-postgresql.postgres
  POSTGRES_PORT: "5432"
  DATABASE_URL: postgresql+asyncpg://skala:Skala25a!23$@postgres-1-postgresql.postgres:5432/cloud
  OPENAI_API_KEY: "Your API Key Here"
