apiVersion: v1
kind: Secret
metadata:
  name: sk047-myservice-secret
  namespace: class-2
type: Opaque
stringData:
  POSTGRES_DB: <your-db-name>
  POSTGRES_USER: <your-db-user>
  POSTGRES_PASSWORD: <your-db-password>
  POSTGRES_HOST: <your-db-host>
  POSTGRES_PORT: "5432"
  DATABASE_URL: postgresql+asyncpg://<user>:<password>@<host>:5432/<db>
  OPENAI_API_KEY: <your-openai-api-key>
