apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-configmaps.yaml
  - 02-secret.yaml
  - 03-pvcs.yaml
  - 11-qdrant.yaml
  - 12-backend.yaml
  - 13-frontend.yaml
  - 20-ingress.yaml
